// packages/react/src/components/Tile.tsx
import React, { memo } from 'react';
import type { Cell } from '@game-frameworks/shared/types';
import styles from '../styles/Tile.module.css';

type Props = {
    cell: Cell;
};

export const Tile: React.FC<Props> = memo(({ cell }) => {
    const { value, position, isNew, mergedFrom } = cell;
    const [row, col] = position;

    const positionStyle: React.CSSProperties = {
        width: `calc((100% - 3 * var(--gap)) / 4)`,
        height: `calc((100% - 3 * var(--gap)) / 4)`,
        left: `calc(${col} * (25% + var(--gap) / 4))`,
        top: `calc(${row} * (25% + var(--gap) / 4))`,
    };

    const classes = [
        styles.tile,
        styles[`tile${value}`],
        isNew ? styles.newTile : '',
        mergedFrom ? styles.mergedTile : '',
    ].join(' ');

    return (
        <div className={classes} style={positionStyle}>
            {value}
        </div>
    );
});

// packages/vue3/src/components/Tile.vue
<template>
  <div :class="[tileStyles.tile, tileStyles[`tile${cell.value}`], isNew && tileStyles.newTile, mergedFrom && tileStyles.mergedTile]" :style="positionStyle">
    {{ cell.value }}
  </div>
</template>

<script setup lang="ts">
import { computed, CSSProperties } from 'vue'
import type { Cell } from '@game-frameworks/shared/types'
import tileStyles from '../styles/Tile.module.css'

interface Props {
  cell: Cell
}

const props = defineProps<Props>()

const isNew = computed(() => props.cell.isNew)
const mergedFrom = computed(() => props.cell.mergedFrom)

const positionStyle = computed<CSSProperties>(() => {
  const [row, col] = props.cell.position
  return {
    width: `calc((100% - 3 * var(--gap)) / 4)`,
    height: `calc((100% - 3 * var(--gap)) / 4)`,
    left: `calc(${col} * (25% + var(--gap) / 4))`,
    top: `calc(${row} * (25% + var(--gap) / 4))`,
  }
})
</script>
